### ISSUE TITLE
Update: Welcome to Coral Beat page

### ISSUE THREAD

**Issue by Bytemarks** [bradbaris/coral-spaceapps#10]
Need to update the Welcome to Coral Beat page with the following text: The coral reefs are sending us a message. Higher temperatures are stressing the corals, causing them to bleach or turn white. Bleaching happens when corals lose the tiny algae that live in and feed the corals. Stressed corals that survive bleaching then begin to starve. Coral reefs play an integral role in the health of our ocean ecosystem. They are home to millions of marine species, directly influence Hawaii’s tourism economy, and protect our shores. We offer this resource for local residents, visitors, and the science community to learn about and help track the effects of bleaching.

**Comment by bradbaris** [comment]
Text updated in 3a382ea
