### ISSUE TITLE
Mask for Hawaiian Islands

### ISSUE THREAD

**Issue by Bytemarks** [bradbaris/coral-spaceapps#11]
I noticed the Hawaiian Islands don't show up on the sea surface temperature map. I thought we had a mask for the island chain. Right now only the Big Island shows up.

**Comment by bradbaris** [comment]
Turns out the API resource we used for the land mask ended up mysteriously disappearing over the past week, hence it not showing up. Temporary fix by substituting it for a 'coastlines' outline map instead.

Fixed in 2ceb88a644a30ac29ef35c66f696b7ab0dfc6aea
